name: Deploy Frontend

on:
  push:
    branches: [feat/ci-setup]  

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::047719641381:role/CDGithubActions
          aws-region: us-east-1

      - name: Sync build to S3
        run: aws s3 sync dist/ s3://g25-arquisis-prueba --delete

      #- name: Invalidate CloudFront cache
      #  run: |
      #    aws cloudfront create-invalidation \
      #      --distribution-id E2SL1XO9OOOE6B \
      #      --paths "/*"
